### ISSUE TITLE
Traceback when using "-c 1"

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#10]
Hi. I am getting the following error when using the "-c 1" switch. (And only then. When using -c 2, it does work without errors.)
weberjoh@jw-nb12:~/dnstools$ ./dnsping.py -c 1 ip.weberdns.de
dnsping.py DNS: 8.8.8.8:53, hostname: ip.weberdns.de, rdatatype: A
43 bytes from 8.8.8.8: seq=0   time=36.177 ms
Traceback (most recent call last):
  File "./dnsping.py", line 212, in <module>
    main()
  File "./dnsping.py", line 199, in main
    r_stddev = stdev(response_time)
  File "/usr/lib/python3.4/statistics.py", line 575, in stdev
    var = variance(data, xbar)
  File "/usr/lib/python3.4/statistics.py", line 513, in variance
    raise StatisticsError('variance requires at least two data points')
statistics.StatisticsError: variance requires at least two data points

**Comment by webernetz** [comment]
That was fast!!!
And works. ;)

weberjoh@jw-nb12:~/dnstools$ ./dnsping.py -c1 blog.webernetz.net
dnsping.py DNS: 8.8.8.8:53, hostname: blog.webernetz.net, rdatatype: A
45 bytes from 8.8.8.8: seq=0   time=21.104 ms

--- 8.8.8.8 dnsping statistics ---
1 requests transmitted, 1 responses received,   0% lost
min=21.104 ms, avg=21.104 ms, max=21.104 ms, stddev=0.000 ms
