### ISSUE TITLE
dnseval: error

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#27]
I am getting errors with dnseval since yesterday. Not everytime, but sometimes. Maybe this is related to DNS names with more than one A record? (Just a guess...)

<pre><code>weberjoh@jw-nb12-lx:~/dnsdiag$ ./dnseval.py -f ../dns-servers de.pool.ntp.org
server                    avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)  ttl     flags
---------------------------------------------------------------------------------------------------------------
194.25.0.68               54.643      4.998       258.121     83.261      %0       118     QR -- -- RD RA -- --
194.25.0.60               10.119      9.068       13.891      1.367       %0       59      QR -- -- RD RA -- --
2003:40:2000::53          7.577       5.078       16.453      3.923       %0       144     QR -- -- RD RA -- --
2003:56::53               11.156      9.683       15.352      1.882       %0       110     QR -- -- RD RA -- --
8.8.8.8                   160.371     14.414      1281.226    395.492     %0       148     QR -- -- RD RA -- --
8.8.4.4                   19.578      15.308      38.391      7.110       %0       147     QR -- -- RD RA -- --
2001:4860:4860::8888      49.517      15.454      248.288     70.513      %0       149     QR -- -- RD RA -- --
2001:4860:4860::8844      21.980      15.918      43.010      7.832       %0       149     QR -- -- RD RA -- --
208.67.222.222            47.215      6.175       248.539     77.963      %0       150     QR -- -- RD RA -- --
208.67.220.220            5.763       4.768       7.042       0.767       %0       149     QR -- -- RD RA -- --
Traceback (most recent call last):
  File "./dnseval.py", line 276, in main
    s, r_avg, r_min, r_max, r_stddev, r_lost_percent, ttl, text_flags), flush=True)
TypeError: a float is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dnseval.py", line 284, in <module>
    main()
  File "./dnseval.py", line 279, in main
    print('%s' % (server, e))
TypeError: not all arguments converted during string formatting
</code></pre>

<pre><code>weberjoh@jw-nb12-lx:~/dnsdiag$ ./dnseval.py -f ../dns-servers 16a.weberdns.de
server                    avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)  ttl     flags
---------------------------------------------------------------------------------------------------------------
194.25.0.68               23.199      11.045      34.717      9.579       %0       3600    QR -- -- RD RA -- --
194.25.0.60               33.624      18.377      45.261      8.735       %0       3600    QR -- -- RD RA -- --
2003:40:2000::53          20.659      12.229      29.553      5.860       %0       3600    QR -- -- RD RA -- --
2003:56::53               23.920      16.153      41.590      8.646       %0       3599    QR -- -- RD RA -- --
8.8.8.8                   242.322     22.335      1087.400    442.411     %0       3599    QR -- -- RD RA AD --
8.8.4.4                   27.212      23.012      32.853      3.128       %0       3598    QR -- -- RD RA AD --
2001:4860:4860::8888      236.299     22.259      1072.441    438.689     %0       3594    QR -- -- RD RA AD --
2001:4860:4860::8844      133.472     25.188      1066.974    328.031     %0       3593    QR -- -- RD RA AD --
208.67.222.222            14.746      11.639      25.024      4.778       %0       3600    QR -- -- RD RA -- --
208.67.220.220            12.524      11.594      17.255      1.741       %0       3600    QR -- -- RD RA -- --
ns1-v4.weberdns.de        14.875      13.569      17.214      0.962       %0       3600    QR AA -- RD -- -- --
ns1-v6.weberdns.de        11.287      11.204      11.609      0.118       %0       3600    QR AA -- RD -- -- --
ns2.weberdns.de           19.289      18.078      20.781      0.934       %0       3600    QR AA -- RD -- -- --
ns3.weberdns.de           33.437      29.666      37.727      3.174       %0       3600    QR AA -- RD -- -- --
int-dns.webernetz.net     10.789      9.901       10.993      0.324       %0       873     QR -- -- RD RA AD --
192.168.110.1             10.847      10.231      15.257      1.552       %0       873     QR -- -- -- -- -- --
192.168.7.1               15.652      13.715      26.419      3.836       %0       3600    QR -- -- RD RA -- --
Traceback (most recent call last):
  File "./dnseval.py", line 276, in main
    s, r_avg, r_min, r_max, r_stddev, r_lost_percent, ttl, text_flags), flush=True)
TypeError: a float is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dnseval.py", line 284, in <module>
    main()
  File "./dnseval.py", line 279, in main
    print('%s' % (server, e))
TypeError: not all arguments converted during string formatting
</code></pre>

**Comment by webernetz** [comment]
Okay, it's also by single host records, such as:

<pre><code>weberjoh@jw-nb12-lx:~/dnsdiag$ ./dnseval.py -f ../dns-servers -t aaaa planes.webernetz.net
server                    avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)  ttl     flags
---------------------------------------------------------------------------------------------------------------
194.25.0.68               109.619     4.567       287.772     110.026     %0       86400   QR -- -- RD RA -- --
194.25.0.60               123.198     8.799       367.820     131.039     %0       86400   QR -- -- RD RA -- --
2003:40:2000::53          35.285      4.606       132.450     45.846      %0       86400   QR -- -- RD RA -- --
2003:56::53               98.916      8.997       299.106     107.730     %0       86398   QR -- -- RD RA -- --
8.8.8.8                   32.100      13.232      48.626      13.134      %0       21599   QR -- -- RD RA -- --
8.8.4.4                   20.500      14.225      42.857      8.393       %0       21598   QR -- -- RD RA -- --
2001:4860:4860::8888      16.489      12.949      20.137      3.499       %0       21598   QR -- -- RD RA -- --
2001:4860:4860::8844      108.235     14.686      649.382     206.187     %0       21597   QR -- -- RD RA -- --
208.67.222.222            21.927      4.161       59.121      20.804      %0       86400   QR -- -- RD RA -- --
208.67.220.220            4.743       3.871       9.982       1.861       %0       86399   QR -- -- RD RA -- --
Traceback (most recent call last):
  File "./dnseval.py", line 276, in main
    s, r_avg, r_min, r_max, r_stddev, r_lost_percent, ttl, text_flags), flush=True)
TypeError: a float is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dnseval.py", line 284, in <module>
    main()
  File "./dnseval.py", line 279, in main
    print('%s' % (server, e))
TypeError: not all arguments converted during string formatting
</code></pre>
