### ISSUE TITLE
All scripts no longer works on Termux

### ISSUE THREAD

**Issue by adithya-s-sekhar** [farrokhi/dnsdiag#69]
Device: Xiaomi Redmi 5 Plus
ROM: Android 8

This used to work a couple of months ago, but know none of the scripts works. Tried the one from pip too.

`$ python dnseval.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/dns/resolver.py", line 743, in read_resolv_conf
    f = stack.enter_context(open(f))
FileNotFoundError: [Errno 2] No such file or directory: '/etc/resolv.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/dnsdiag/dnseval.py", line 51, in <module>
    resolvers = dns.resolver.get_default_resolver().nameservers
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/dns/resolver.py", line 1178, in get_default_resolver
    reset_default_resolver()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/dns/resolver.py", line 1190, in reset_default_resolver
    default_resolver = Resolver()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/dns/resolver.py", line 695, in __init__
    self.read_resolv_conf(filename)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/dns/resolver.py", line 746, in read_resolv_conf
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.`

**Comment by adithya-s-sekhar** [comment]
Just noticed etc/resolve.conf doesn't exist in my rom, still manually providing the server with -s shows the same error.

**Comment by farrokhi** [comment]
This seems to be an edge case not being properly handled in [dnspython](https://github.com/rthalley/dnspython)
can you manually upgrade to latest `dnspython` and see if this still happens? Something like `pip3 install --upgrade dnspython` should do the trick.

**Comment by adithya-s-sekhar** [comment]
Just tried it, it's up to date. Still doesn't work.

**Comment by farrokhi** [comment]
Seems like `dnspython` strictly assumes there should be a `/etc/resolv.conf` available. I suggest opening a case with them to address this edge case.

**Comment by farrokhi** [comment]
I am also considering to ditch the stub resolver (that depends on `/etc/resolv.conf`). That may address this issue.

**Comment by farrokhi** [comment]
Fixed in version 2.0.0 d6aab02d8301ee9c0ec97d9997932061befb903e
